version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/prod
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prod
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
